### ISSUE TITLE
Unexpected exit

### ISSUE THREAD

**Issue by aknight2015** [JacobBruce/CosmicVoid#1]
I'm using the Windows release. I run it and it creates the OpenGL window, then closes out. Doesn't display anything.

**Comment by JacobBruce** [comment]
I'm guessing you are using an nvidia card. Try replacing the Data/kernels/compute.cl file with the latest version. It should make Cosmic Void run but there are still other rendering issues with nvidia cards.

**Comment by aknight2015** [comment]
I can try and use my laptops integrated graphics. I'm not sure what you mean by "latest version."

Update: Using Windows Graphics Settings I manually added CosmicVoid.exe and selected the integrated CPU graphics.

![InkedScreenshot 2021-07-24 080548_LI](https://user-images.githubusercontent.com/47067592/126867973-5eddc18b-0c6e-4bda-8edf-de858caebc82.jpg)
![Screenshot 2021-07-24 080628](https://user-images.githubusercontent.com/47067592/126867974-61ba6e98-52d1-4655-b10c-8360604c095b.png)
![Screenshot 2021-07-24 080653](https://user-images.githubusercontent.com/47067592/126867975-1543f440-14b4-4d87-9785-3810a8d501ca.png)

**Comment by JacobBruce** [comment]
I mean the latest version from this repo and not from the release archive. So did it work with your integrated Intel graphics chip? In theory it should work if your GPU supports OpenCL but it should definitely work on most AMD cards since that's what I used to develop Cosmic Void.

**Comment by aknight2015** [comment]
Gotcha. Well, it's working. I will try the latest release via the repo as well.

**Comment by JacobBruce** [comment]
Issue with Nvidia cards should be fixed in v0.1.0 so I'm closing this issue. It's now using OpenCL 3 so make sure you're drivers are up to date.
